name: LobsterDataImport

on:
  push:
    paths:
      - .github/workflow/flat.yaml
  workflow_dispatch:
  schedule:
    - cron '*/60 * * * *'
    
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: fetch_data
        uses: githubocto/flat@v3
        with:
          http_url: https://lobste.rs/newest.json
          download_file: newest.json
